/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Category = IDL.Variant({
  'other' : IDL.Null,
  'biki' : IDL.Null,
  'rideshare' : IDL.Null,
  'theBus' : IDL.Null,
  'walking' : IDL.Null,
  'trolley' : IDL.Null,
  'carRental' : IDL.Null,
});
export const TransportEntryInput = IDL.Record({
  'title' : IDL.Text,
  'tips' : IDL.Text,
  'description' : IDL.Text,
  'pricing' : IDL.Text,
  'category' : Category,
});
export const TransportEntry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'tips' : IDL.Text,
  'description' : IDL.Text,
  'pricing' : IDL.Text,
  'category' : Category,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addEntry' : IDL.Func([TransportEntryInput], [IDL.Nat], []),
  'deleteEntry' : IDL.Func([IDL.Nat], [], []),
  'getAllEntries' : IDL.Func([], [IDL.Vec(TransportEntry)], ['query']),
  'getEntriesByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(TransportEntry)],
      ['query'],
    ),
  'getEntry' : IDL.Func([IDL.Nat], [TransportEntry], ['query']),
  'updateEntry' : IDL.Func([IDL.Nat, TransportEntryInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Category = IDL.Variant({
    'other' : IDL.Null,
    'biki' : IDL.Null,
    'rideshare' : IDL.Null,
    'theBus' : IDL.Null,
    'walking' : IDL.Null,
    'trolley' : IDL.Null,
    'carRental' : IDL.Null,
  });
  const TransportEntryInput = IDL.Record({
    'title' : IDL.Text,
    'tips' : IDL.Text,
    'description' : IDL.Text,
    'pricing' : IDL.Text,
    'category' : Category,
  });
  const TransportEntry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'tips' : IDL.Text,
    'description' : IDL.Text,
    'pricing' : IDL.Text,
    'category' : Category,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addEntry' : IDL.Func([TransportEntryInput], [IDL.Nat], []),
    'deleteEntry' : IDL.Func([IDL.Nat], [], []),
    'getAllEntries' : IDL.Func([], [IDL.Vec(TransportEntry)], ['query']),
    'getEntriesByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(TransportEntry)],
        ['query'],
      ),
    'getEntry' : IDL.Func([IDL.Nat], [TransportEntry], ['query']),
    'updateEntry' : IDL.Func([IDL.Nat, TransportEntryInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };